name: The Recipe Master

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-versions: 1.8

      - name: Run Tests
        run: ./gradlew test

      - name: Build Projects
        run: ./gradlew assemble